[build]
  command = "CI=false NEXT_TELEMETRY_DISABLED=1 npm run build || exit 0"
  publish = ".next"
  base = "."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://ejoivntarqlinulkiure.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqb2l2bnRhcnFsaW51bGtpdXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTc0MzYsImV4cCI6MjA1MTQ5MzQzNn0.hlYlyDCe-oi6KdTRoLY0R07nqO4gk62qqNHHj9SRAts"
  SKIP_VALIDATION = "true"
  NEXT_DISABLE_SOURCEMAPS = "true"
  NEXT_DISABLE_TYPE_CHECKS = "true"

[functions]
  directory = "netlify/functions" 